<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 8 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|Location)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Location EMPTY>
<!ATTLIST Location
  date               CDATA #REQUIRED
  latitude           CDATA #REQUIRED
  longitude          CDATA #REQUIRED
  altitude           CDATA #REQUIRED
  horizontalAccuracy CDATA #REQUIRED
  verticalAccuracy   CDATA #REQUIRED
  course             CDATA #REQUIRED
  speed              CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
]>
<HealthData locale="en_DE">
 <ExportDate value="2018-10-10 16:58:34 +0200"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="1984-05-07" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-15 15:51:45 +0200" startDate="2018-07-15 15:51:40 +0200" endDate="2018-07-15 15:51:40 +0200" value="22.1"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-15 15:52:12 +0200" startDate="2018-07-15 15:52:12 +0200" endDate="2018-07-15 15:52:12 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-15 15:52:45 +0200" startDate="2018-07-15 15:52:45 +0200" endDate="2018-07-15 15:52:45 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-16 08:03:54 +0200" startDate="2018-07-16 08:03:54 +0200" endDate="2018-07-16 08:03:54 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-16 22:28:39 +0200" startDate="2018-07-16 22:28:39 +0200" endDate="2018-07-16 22:28:39 +0200" value="22.3"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-17 22:25:24 +0200" startDate="2018-07-17 22:25:12 +0200" endDate="2018-07-17 22:25:12 +0200" value="22.4"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-17 22:25:30 +0200" startDate="2018-07-17 22:25:30 +0200" endDate="2018-07-17 22:25:30 +0200" value="22.4"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-18 09:04:07 +0200" startDate="2018-07-18 09:04:07 +0200" endDate="2018-07-18 09:04:07 +0200" value="22"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-21 08:42:24 +0200" startDate="2018-07-21 08:42:24 +0200" endDate="2018-07-21 08:42:24 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-22 12:25:04 +0200" startDate="2018-07-22 12:25:04 +0200" endDate="2018-07-22 12:25:04 +0200" value="22.3"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-23 07:27:08 +0200" startDate="2018-07-23 07:27:08 +0200" endDate="2018-07-23 07:27:08 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-24 09:13:10 +0200" startDate="2018-07-24 09:13:10 +0200" endDate="2018-07-24 09:13:10 +0200" value="22.1"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-25 07:47:35 +0200" startDate="2018-07-25 07:47:35 +0200" endDate="2018-07-25 07:47:35 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-26 08:58:53 +0200" startDate="2018-07-26 08:58:53 +0200" endDate="2018-07-26 08:58:53 +0200" value="22.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-27 09:09:33 +0200" startDate="2018-07-27 09:09:33 +0200" endDate="2018-07-27 09:09:33 +0200" value="22"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-28 10:16:49 +0200" startDate="2018-07-28 10:16:49 +0200" endDate="2018-07-28 10:16:49 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-29 11:01:10 +0200" startDate="2018-07-29 11:01:10 +0200" endDate="2018-07-29 11:01:10 +0200" value="21.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-30 09:12:39 +0200" startDate="2018-07-30 09:12:39 +0200" endDate="2018-07-30 09:12:39 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-07-31 07:29:11 +0200" startDate="2018-07-31 07:29:10 +0200" endDate="2018-07-31 07:29:10 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-01 08:07:06 +0200" startDate="2018-08-01 08:07:06 +0200" endDate="2018-08-01 08:07:06 +0200" value="21.9"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-02 07:52:41 +0200" startDate="2018-08-02 07:52:41 +0200" endDate="2018-08-02 07:52:41 +0200" value="21.9"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-03 08:21:16 +0200" startDate="2018-08-03 08:21:16 +0200" endDate="2018-08-03 08:21:16 +0200" value="21.9"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-04 08:46:49 +0200" startDate="2018-08-04 08:46:49 +0200" endDate="2018-08-04 08:46:49 +0200" value="21.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-05 10:14:05 +0200" startDate="2018-08-05 10:14:05 +0200" endDate="2018-08-05 10:14:05 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-06 08:52:27 +0200" startDate="2018-08-06 08:52:27 +0200" endDate="2018-08-06 08:52:27 +0200" value="21.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-07 06:58:43 +0200" startDate="2018-08-07 06:58:43 +0200" endDate="2018-08-07 06:58:43 +0200" value="21.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-08 08:25:46 +0200" startDate="2018-08-08 08:25:45 +0200" endDate="2018-08-08 08:25:45 +0200" value="22"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-09 07:58:53 +0200" startDate="2018-08-09 07:58:53 +0200" endDate="2018-08-09 07:58:53 +0200" value="21.8"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-10 07:39:12 +0200" startDate="2018-08-10 07:39:12 +0200" endDate="2018-08-10 07:39:12 +0200" value="21.9"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-08-10 07:39:30 +0200" startDate="2018-08-10 07:39:30 +0200" endDate="2018-08-10 07:39:30 +0200" value="21.9"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-11 08:28:13 +0200" startDate="2018-08-11 08:28:13 +0200" endDate="2018-08-11 08:28:13 +0200" value="21.9"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-12 10:44:04 +0200" startDate="2018-08-12 10:44:04 +0200" endDate="2018-08-12 10:44:04 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-13 09:10:38 +0200" startDate="2018-08-13 09:10:38 +0200" endDate="2018-08-13 09:10:38 +0200" value="21.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-14 08:08:55 +0200" startDate="2018-08-14 08:08:55 +0200" endDate="2018-08-14 08:08:55 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-15 07:37:54 +0200" startDate="2018-08-15 07:37:53 +0200" endDate="2018-08-15 07:37:53 +0200" value="21.8"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-16 06:57:07 +0200" startDate="2018-08-16 06:57:07 +0200" endDate="2018-08-16 06:57:07 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-17 07:42:50 +0200" startDate="2018-08-17 07:42:50 +0200" endDate="2018-08-17 07:42:50 +0200" value="21.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-18 08:31:25 +0200" startDate="2018-08-18 08:31:25 +0200" endDate="2018-08-18 08:31:25 +0200" value="21.4"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="2" unit="count" creationDate="2018-08-19 08:28:48 +0200" startDate="2018-08-19 08:28:48 +0200" endDate="2018-08-19 08:28:48 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-15 08:12:41 +0200" startDate="2018-09-15 08:12:41 +0200" endDate="2018-09-15 08:12:41 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-16 07:16:12 +0200" startDate="2018-09-16 07:16:12 +0200" endDate="2018-09-16 07:16:12 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-17 08:31:32 +0200" startDate="2018-09-17 08:31:32 +0200" endDate="2018-09-17 08:31:32 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-18 07:40:09 +0200" startDate="2018-09-18 07:40:09 +0200" endDate="2018-09-18 07:40:09 +0200" value="21.4"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-19 07:59:21 +0200" startDate="2018-09-19 07:59:21 +0200" endDate="2018-09-19 07:59:21 +0200" value="21.3"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-20 07:06:21 +0200" startDate="2018-09-20 07:06:21 +0200" endDate="2018-09-20 07:06:21 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-21 07:07:58 +0200" startDate="2018-09-21 07:07:57 +0200" endDate="2018-09-21 07:07:57 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-22 11:06:33 +0200" startDate="2018-09-22 11:06:33 +0200" endDate="2018-09-22 11:06:33 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-22 11:06:53 +0200" startDate="2018-09-22 11:06:53 +0200" endDate="2018-09-22 11:06:53 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-23 10:18:56 +0200" startDate="2018-09-23 10:18:56 +0200" endDate="2018-09-23 10:18:56 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-24 07:56:22 +0200" startDate="2018-09-24 07:56:22 +0200" endDate="2018-09-24 07:56:22 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-25 07:27:56 +0200" startDate="2018-09-25 07:27:56 +0200" endDate="2018-09-25 07:27:56 +0200" value="21.4"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-25 07:28:09 +0200" startDate="2018-09-25 07:28:09 +0200" endDate="2018-09-25 07:28:09 +0200" value="21.4"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-26 07:38:03 +0200" startDate="2018-09-26 07:38:03 +0200" endDate="2018-09-26 07:38:03 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-27 07:25:39 +0200" startDate="2018-09-27 07:25:39 +0200" endDate="2018-09-27 07:25:39 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-29 07:27:34 +0200" startDate="2018-09-29 07:27:34 +0200" endDate="2018-09-29 07:27:34 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-30 09:16:18 +0200" startDate="2018-09-30 09:15:33 +0200" endDate="2018-09-30 09:15:33 +0200" value="21.8"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-09-30 09:16:19 +0200" startDate="2018-09-30 09:16:19 +0200" endDate="2018-09-30 09:16:19 +0200" value="21.8"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-01 08:10:42 +0200" startDate="2018-10-01 08:10:16 +0200" endDate="2018-10-01 08:10:16 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-01 08:10:49 +0200" startDate="2018-10-01 08:10:49 +0200" endDate="2018-10-01 08:10:49 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-02 07:13:03 +0200" startDate="2018-10-02 07:13:03 +0200" endDate="2018-10-02 07:13:03 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-03 08:12:25 +0200" startDate="2018-10-03 08:12:24 +0200" endDate="2018-10-03 08:12:24 +0200" value="21.3"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-04 07:52:46 +0200" startDate="2018-10-04 07:52:46 +0200" endDate="2018-10-04 07:52:46 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-05 07:32:17 +0200" startDate="2018-10-05 07:32:17 +0200" endDate="2018-10-05 07:32:17 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-06 07:47:48 +0200" startDate="2018-10-06 07:47:48 +0200" endDate="2018-10-06 07:47:48 +0200" value="22.1"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-06 16:57:31 +0200" startDate="2018-10-06 16:57:31 +0200" endDate="2018-10-06 16:57:31 +0200" value="21.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-07 09:39:33 +0200" startDate="2018-10-07 09:39:33 +0200" endDate="2018-10-07 09:39:33 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-08 07:26:23 +0200" startDate="2018-10-08 07:26:23 +0200" endDate="2018-10-08 07:26:23 +0200" value="21.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="1" unit="count" creationDate="2018-10-09 07:12:28 +0200" startDate="2018-10-09 07:12:28 +0200" endDate="2018-10-09 07:12:28 +0200" value="21.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="RENPHO" sourceVersion="7" unit="count" creationDate="2018-10-10 08:29:25 +0200" startDate="2018-10-10 08:29:25 +0200" endDate="2018-10-10 08:29:25 +0200" value="21.6"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-15 15:51:45 +0200" startDate="2018-07-15 15:51:23 +0200" endDate="2018-07-15 15:51:23 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-16 08:03:17 +0200" startDate="2018-07-16 08:03:17 +0200" endDate="2018-07-16 08:03:17 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-16 12:54:56 +0200" startDate="2018-07-16 12:54:56 +0200" endDate="2018-07-16 12:54:56 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-16 22:28:20 +0200" startDate="2018-07-16 22:28:19 +0200" endDate="2018-07-16 22:28:19 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-17 09:00:05 +0200" startDate="2018-07-17 09:00:05 +0200" endDate="2018-07-17 09:00:05 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-17 22:31:13 +0200" startDate="2018-07-17 22:31:13 +0200" endDate="2018-07-17 22:31:13 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-20 09:59:15 +0200" startDate="2018-07-20 09:59:15 +0200" endDate="2018-07-20 09:59:15 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-20 22:04:33 +0200" startDate="2018-07-20 22:04:33 +0200" endDate="2018-07-20 22:04:33 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-07-22 12:19:55 +0200" startDate="2018-07-22 12:19:55 +0200" endDate="2018-07-22 12:19:55 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="2" unit="cm" creationDate="2018-08-11 08:27:56 +0200" startDate="2018-08-11 08:27:52 +0200" endDate="2018-08-11 08:27:52 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-10 02:21:07 +0200" startDate="2018-09-10 02:21:07 +0200" endDate="2018-09-10 02:21:07 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-15 10:25:58 +0200" startDate="2018-09-15 10:25:58 +0200" endDate="2018-09-15 10:25:58 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-24 12:00:09 +0200" startDate="2018-09-24 12:00:09 +0200" endDate="2018-09-24 12:00:09 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-28 10:03:46 +0200" startDate="2018-09-28 10:03:46 +0200" endDate="2018-09-28 10:03:46 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-29 07:06:00 +0200" startDate="2018-09-29 07:06:00 +0200" endDate="2018-09-29 07:06:00 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-29 07:07:44 +0200" startDate="2018-09-29 07:07:44 +0200" endDate="2018-09-29 07:07:44 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-29 07:08:59 +0200" startDate="2018-09-29 07:08:58 +0200" endDate="2018-09-29 07:08:58 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-09-29 07:10:37 +0200" startDate="2018-09-29 07:10:37 +0200" endDate="2018-09-29 07:10:37 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="1" unit="cm" creationDate="2018-10-09 16:14:09 +0200" startDate="2018-10-09 16:14:09 +0200" endDate="2018-10-09 16:14:09 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="RENPHO" sourceVersion="7" unit="cm" creationDate="2018-10-09 23:04:07 +0200" startDate="2018-10-09 23:04:07 +0200" endDate="2018-10-09 23:04:07 +0200" value="176"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-15 15:51:45 +0200" startDate="2018-07-15 15:51:40 +0200" endDate="2018-07-15 15:51:40 +0200" value="68.5"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-15 15:52:12 +0200" startDate="2018-07-15 15:52:12 +0200" endDate="2018-07-15 15:52:12 +0200" value="68.65"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-15 15:52:45 +0200" startDate="2018-07-15 15:52:45 +0200" endDate="2018-07-15 15:52:45 +0200" value="68.65"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-16 08:03:54 +0200" startDate="2018-07-16 08:03:54 +0200" endDate="2018-07-16 08:03:54 +0200" value="68.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-16 22:28:39 +0200" startDate="2018-07-16 22:28:39 +0200" endDate="2018-07-16 22:28:39 +0200" value="69"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-17 22:25:24 +0200" startDate="2018-07-17 22:25:12 +0200" endDate="2018-07-17 22:25:12 +0200" value="69.25"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-17 22:25:30 +0200" startDate="2018-07-17 22:25:30 +0200" endDate="2018-07-17 22:25:30 +0200" value="69.25"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-18 09:04:07 +0200" startDate="2018-07-18 09:04:07 +0200" endDate="2018-07-18 09:04:07 +0200" value="68.2"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-21 08:42:24 +0200" startDate="2018-07-21 08:42:24 +0200" endDate="2018-07-21 08:42:24 +0200" value="68.65"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-22 12:25:04 +0200" startDate="2018-07-22 12:25:04 +0200" endDate="2018-07-22 12:25:04 +0200" value="68.95"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-23 07:27:08 +0200" startDate="2018-07-23 07:27:08 +0200" endDate="2018-07-23 07:27:08 +0200" value="68.85"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-24 09:13:10 +0200" startDate="2018-07-24 09:13:10 +0200" endDate="2018-07-24 09:13:10 +0200" value="68.55"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-25 07:47:35 +0200" startDate="2018-07-25 07:47:35 +0200" endDate="2018-07-25 07:47:35 +0200" value="68.65"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-26 08:58:53 +0200" startDate="2018-07-26 08:58:53 +0200" endDate="2018-07-26 08:58:53 +0200" value="68.75"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-27 09:09:33 +0200" startDate="2018-07-27 09:09:33 +0200" endDate="2018-07-27 09:09:33 +0200" value="68.15"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-28 10:16:49 +0200" startDate="2018-07-28 10:16:49 +0200" endDate="2018-07-28 10:16:49 +0200" value="66.6"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-29 11:01:10 +0200" startDate="2018-07-29 11:01:10 +0200" endDate="2018-07-29 11:01:10 +0200" value="67.35"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-30 09:12:39 +0200" startDate="2018-07-30 09:12:39 +0200" endDate="2018-07-30 09:12:39 +0200" value="66.8"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-07-31 07:29:11 +0200" startDate="2018-07-31 07:29:10 +0200" endDate="2018-07-31 07:29:10 +0200" value="67"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-08-01 08:07:06 +0200" startDate="2018-08-01 08:07:06 +0200" endDate="2018-08-01 08:07:06 +0200" value="67.8"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-08-02 07:52:41 +0200" startDate="2018-08-02 07:52:41 +0200" endDate="2018-08-02 07:52:41 +0200" value="67.7"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="RENPHO" sourceVersion="1" unit="kg" creationDate="2018-08-03 08:21:16 +0200" startDate="2018-08-03 08:21:16 +0200" endDate="2018-08-03 08:21:16 +0200" value="67.7"/>